# Generated by Django 3.2.5 on 2022-03-17 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('execute_time', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubTaskTaskRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(blank=True, max_length=255)),
                ('bool', models.BooleanField(default=False)),
                ('bool2', models.BooleanField(default=False)),
                ('time', models.PositiveIntegerField(choices=[(1, 'Ok'), (2, 'Fine'), (3, 'Good'), (4, 'Amazing'), (5, 'Incredible')], null=True)),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subtask')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('task', models.TextField(verbose_name='описание')),
                ('base_count', models.IntegerField(default=100)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True)),
                ('bool_count', models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True)),
                ('owner', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('subtask', models.ManyToManyField(related_name='task', through='main.SubTaskTaskRelations', to='main.SubTask')),
            ],
        ),
        migrations.AddField(
            model_name='subtasktaskrelations',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task'),
        ),
    ]
